/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clients;


import MaHoa.AESClient;
import MaHoa.EncryptKeyAES;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.net.Socket;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;

public class FormChat extends javax.swing.JFrame {

    // vl đây rồi, đây là biến toàn cục, khi mà client 2 chay sẽ khởi tạo mới, đè lên thằng client 1 luôn ew
//    private static BufferedReader stdIn = null;
    private static String line;
    private static String input;
    
    private Client c ;

    public FormChat() throws Exception {
        c = new Client();
        
        initComponents();
        
        this.setLocationRelativeTo(null);

    }

    public void connectToServer(String input) {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lb_chatbot = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        txtNhap = new javax.swing.JTextField();
        btnGui = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        lb_chatbot.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        lb_chatbot.setText("ChatBot");
        lb_chatbot.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_chatbot.setInheritsPopupMenu(false);
        jPanel1.add(lb_chatbot);
        lb_chatbot.setBounds(20, 20, 130, 30);

        txtArea.setColumns(20);
        txtArea.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtArea.setRows(5);
        txtArea.setToolTipText("");
        jScrollPane1.setViewportView(txtArea);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 60, 900, 550);

        txtNhap.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNhap.setToolTipText("");
        txtNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNhapActionPerformed(evt);
            }
        });
        jPanel1.add(txtNhap);
        txtNhap.setBounds(20, 620, 800, 40);

        btnGui.setText("Gửi");
        btnGui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuiActionPerformed(evt);
            }
        });
        btnGui.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnGuiKeyPressed(evt);
            }
        });
        jPanel1.add(btnGui);
        btnGui.setBounds(830, 620, 90, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 947, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNhapActionPerformed
        this.btnGui.requestFocus();
        this.btnGui.doClick();
        this.txtNhap.setText("");

    }//GEN-LAST:event_txtNhapActionPerformed

    private void btnGuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuiActionPerformed
        try {
            input = txtNhap.getText();
            txtArea.append("Bạn: " + input + "\r\n");
            System.out.println("aaaa" + input);

            if (input.equals("chuyentien")) {
                CurrencyConverterForm currency = new CurrencyConverterForm(c);
                currency.setVisible(true);

                // nếu bye thì đóng connection
            } else if (input.equals("bye")) {
                txtArea.append("bái bai" + "\r\n");
                c.sendClient(input);
                c.dongKetNoi();
            }
            
            
            // Mã hóa gửi cho sv:
            input = AESClient.encrypt(input);
            c.sendClient(input);

            // server response:
            // Giải mã thông điệp từ sv
            
           

        } catch (Exception ex) {
            System.out.println(ex);
        }

    }//GEN-LAST:event_btnGuiActionPerformed

   
    private void btnGuiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnGuiKeyPressed
//        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
//
//            input = txtNhap.getText();
//            txtArea.append(input + "\r\n");
//
//            String weather = "";
//            if (input.equals("chuyendoitien")) {
//                CurrencyConverterForm currency = new CurrencyConverterForm();
//                currency.setVisible(true);

//            } else {
//          txtArea.append(Simsimi.getResponeFromSimsimi(input) + "\r\n");
//           weather = thoiTiet.getWeather(input);
//          txtArea.setText(weather);
//            }
//        }

    }//GEN-LAST:event_btnGuiKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws Exception {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
       
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FormChat().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(FormChat.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

        

    } //

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGui;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_chatbot;
    public static javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txtNhap;
    // End of variables declaration//GEN-END:variables
}
